import type { AgentAction, CursorWorkOrder } from "../types.js";
import {
  renderCompletionContractSection,
  type CompletionContractIdentity,
} from "./completion-contract.js";
import { deriveHardProhibitionsFromWorkOrderScope } from "./work-order-scope.js";

const AGENT_ACTION_LABELS: Record<AgentAction, string> = {
  REUSE_CURRENT_AGENT: "REUSE CURRENT AGENT",
  FRESH_ORDINARY_AGENT_REQUIRED: "FRESH ORDINARY AGENT REQUIRED",
  FRESH_API_CREATED_PARENT_AUTO_REQUIRED: "FRESH API CREATED PARENT AUTO REQUIRED",
};

export interface RenderCursorPromptOptions extends CompletionContractIdentity {}

/**
 * Render a human-readable Cursor prompt from a structured work order.
 *
 * Completion-output contract is derived from the canonical schema via
 * completion-contract.ts — not a parallel handwritten field list.
 */
export function renderCursorPrompt(
  workOrder: CursorWorkOrder,
  options: RenderCursorPromptOptions = {},
): string {
  const agentLabel = AGENT_ACTION_LABELS[workOrder.agentAction];
  const lines: string[] = [];
  const allowsProductEdits = workOrder.scope.allowedProductChanges.length > 0;
  const trustedSha = workOrder.source.expectedBaseTipSha?.trim() || "";
  const trustedBranch =
    workOrder.source.workingBranch?.trim() ||
    workOrder.source.baseBranch?.trim() ||
    "";

  lines.push(`AGENT REQUIREMENT: ${agentLabel}`);
  lines.push("");
  if (allowsProductEdits) {
    lines.push(
      "You are implementing a Radio-controlled bounded product transaction.",
    );
    lines.push(
      "Perform only the authorized requestedWork. Do not widen into prohibited scope.",
    );
  } else {
    lines.push("You are implementing a Radio-controlled verification transaction.");
    lines.push("This is a bounded, read-only technical verification task.");
  }
  lines.push("");

  // Completion contract is intentionally near the top so Cursor cannot treat
  // it as an optional trailing reporting suggestion.
  if (workOrder.rendering.includeCompletionContract) {
    lines.push(renderCompletionContractSection(workOrder, options));
    lines.push("");
  }

  if (workOrder.rendering.includeStructuredIdentity) {
    lines.push("==================================================");
    lines.push("WORK ORDER IDENTITY");
    lines.push("==================================================");
    lines.push(`workOrderId: ${workOrder.workOrderId}`);
    lines.push(`decisionId: ${workOrder.decisionId}`);
    lines.push(`projectId: ${workOrder.projectId}`);
    lines.push(`workstreamId: ${workOrder.workstreamId}`);
    lines.push(`transactionId: ${workOrder.transactionId}`);
    lines.push(`idempotencyKey: ${workOrder.idempotencyKey}`);
    lines.push(`agentAction: ${workOrder.agentAction}`);
    lines.push(`workType: ${workOrder.workType}`);
    if (options.plannedAgentId) {
      lines.push(
        `plannedOrdinaryAgentId: ${options.plannedAgentId} (IMMUTABLE — use in execution.ordinaryAgent.agentId)`,
      );
    }
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("OBJECTIVE");
  lines.push("==================================================");
  lines.push(workOrder.objective);
  lines.push("");

  lines.push("==================================================");
  lines.push("REQUESTED WORK");
  lines.push("==================================================");
  lines.push(workOrder.requestedWork);
  lines.push("");

  lines.push("==================================================");
  lines.push("ACCEPTANCE / VERIFICATION CRITERIA");
  lines.push("==================================================");
  lines.push(workOrder.verificationCriteria);
  lines.push("");

  lines.push("==================================================");
  lines.push("RADIO ENFORCED GUARDRAILS");
  lines.push("==================================================");
  lines.push(
    "The following constraints are generated by Radio from trusted authority/policy state.",
  );
  lines.push(
    "They are NOT Sol-requested executable work and do not expand or shrink objective authority.",
  );
  for (const g of workOrder.radioGuardrails) {
    lines.push(`- ${g}`);
  }
  lines.push("");

  if (workOrder.rendering.includeSourcePins) {
    lines.push("==================================================");
    lines.push("REPOSITORY INTEGRITY — MANDATORY FIRST CHECK");
    lines.push("==================================================");
    lines.push(
      "Before any substantive verification, product inspection, tests, builds, commits, PRs, or remediation:",
    );
    lines.push("1. Run: git rev-parse HEAD");
    if (trustedSha) {
      lines.push(`2. Required exact value (Radio-authorized trusted SHA): ${trustedSha}`);
      lines.push(
        `TRUSTED SOURCE IDENTITY (ObjectiveAuthority / Radio pin — not worker choice):`,
      );
      lines.push(`  - trusted branch/ref: ${trustedBranch || "(missing)"}`);
      lines.push(`  - trusted full SHA: ${trustedSha}`);
      lines.push(
        "3. If HEAD already equals the required exact value: proceed to requested work.",
      );
      lines.push(
        "4. If HEAD differs (e.g. cloud workspace initialized on repository default/main despite Cursor startingRef):",
      );
      lines.push(
        "   - You are AUTHORIZED and REQUIRED to materialize the Radio-authorized source before any product work:",
      );
      lines.push(
        `   - fetch the trusted ref as needed (branch/ref: ${trustedBranch || trustedSha})`,
      );
      lines.push(
        `   - checkout the exact trusted full commit ${trustedSha} (detached OK) or the trusted branch only if it resolves to that exact SHA`,
      );
      lines.push(`   - re-run: git rev-parse HEAD`);
      lines.push(
        `   - REQUIRED: HEAD must exactly equal ${trustedSha} before any product inspection or edit`,
      );
      lines.push(
        "   - Do NOT invent an alternate source. Do NOT fall back to main. Do NOT choose a different SHA.",
      );
      lines.push(
        "5. If authorized materialization fails or HEAD still does not exactly equal the trusted SHA:",
      );
      lines.push("   - STOP immediately");
      lines.push("   - Perform NO product inspection or edits");
      lines.push("   - Perform NO verification work beyond recording the precheck failure");
      lines.push("   - Perform NO commits");
      lines.push("   - Perform NO PR");
      lines.push("   - Perform NO remediation");
      lines.push(
        "   - STILL return schema-valid completion-report JSON inside exactly one fenced `text` block",
      );
      lines.push(
        '   - Encode blocked/precheck outcome with execution.status="PRECHECK_BLOCKED", resultClass="BLOCKED", tests/build NOT_RUN, no product changes',
      );
      lines.push(
        "   - Return a blocked result (HALT_PRECHECK) as canonical JSON — never prose",
      );
      lines.push(
        "6. Worker prose claiming \"I checked out the branch\" is NOT authority — only git rev-parse HEAD vs the trusted full SHA is.",
      );
    } else {
      lines.push("2. Required exact value: (missing from work order — halt)");
      lines.push("3. If HEAD cannot be verified against a trusted SHA: STOP immediately.");
    }
    lines.push("");
    lines.push("==================================================");
    lines.push("REPOSITORY AND SOURCE PINS");
    lines.push("==================================================");
    lines.push(`Repository: ${workOrder.source.repository}`);
    lines.push(
      `Integration branch: ${workOrder.source.canonicalMainBranch}`,
    );
    lines.push(
      `Integration SHA (reported): ${workOrder.source.canonicalMainSha ?? "null"}`,
    );
    lines.push(`Authorized base branch: ${workOrder.source.baseBranch}`);
    lines.push(
      `Authorized expected tip (authoritative): ${workOrder.source.expectedBaseTipSha ?? "null"}`,
    );
    lines.push(
      `Expected executable ancestor SHA: ${workOrder.source.expectedExecutableAncestorSha ?? "null"}`,
    );
    lines.push(
      `Working branch: ${workOrder.source.workingBranch ?? "null"}`,
    );
    lines.push(
      `Create working branch: ${workOrder.source.createWorkingBranch}`,
    );
    lines.push("");
    lines.push("REQUIRED PRECHECK:");
    lines.push(
      "Verify these repository/branch/SHA facts before trusting them. Materialize the Radio-authorized source if needed. Do not invent repository state. If observed HEAD still differs after authorized materialization, halt with PRECHECK_BLOCKED JSON (not prose).",
    );
    lines.push("");
  }

  if (workOrder.rendering.includeScope) {
    lines.push("==================================================");
    lines.push("IN SCOPE");
    lines.push("==================================================");
    for (const item of workOrder.scope.inScope) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    lines.push("==================================================");
    lines.push("OUT OF SCOPE / PROHIBITED");
    lines.push("==================================================");
    for (const item of workOrder.scope.outOfScope) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    if (workOrder.scope.allowedProductChanges.length === 0) {
      lines.push("allowedProductChanges: (empty — no product edits)");
    } else {
      lines.push("allowedProductChanges:");
      for (const item of workOrder.scope.allowedProductChanges) {
        lines.push(`- ${item}`);
      }
    }
    lines.push("Protected semantics:");
    for (const item of workOrder.scope.protectedSemantics) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    lines.push("Hard prohibitions:");
    for (const item of deriveHardProhibitionsFromWorkOrderScope(
      workOrder.scope,
    )) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("REQUIREMENTS");
  lines.push("==================================================");
  for (const req of workOrder.requirements) {
    lines.push(`[${req.id}] (${req.class}/${req.priority}) ${req.statement}`);
    lines.push(`  Acceptance: ${req.acceptanceMethod}`);
  }
  lines.push("");

  if (workOrder.rendering.includeBudgets) {
    lines.push("==================================================");
    lines.push("BUDGETS");
    lines.push("==================================================");
    lines.push(`maxRemediationPasses: ${workOrder.budgets.maxRemediationPasses}`);
    lines.push(
      `maxSpecialistReviewCycles: ${workOrder.budgets.maxSpecialistReviewCycles}`,
    );
    lines.push(`maxAgents: ${workOrder.budgets.maxAgents}`);
    lines.push(
      `maxEstimatedUsd: ${workOrder.budgets.maxEstimatedUsd ?? "null"}`,
    );
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("VERIFICATION COMMANDS");
  lines.push("==================================================");
  for (const cmd of workOrder.verification.requiredCommands) {
    lines.push(`- ${cmd}`);
  }
  lines.push("");

  lines.push("==================================================");
  lines.push("GIT / PR RESTRICTIONS");
  lines.push("==================================================");
  lines.push(
    `Protected branches: ${workOrder.git.protectedBranches.join(", ")}`,
  );
  lines.push(`pushRequired: ${workOrder.git.pushRequired}`);
  lines.push(`forcePushAllowed: ${workOrder.git.forcePushAllowed}`);
  lines.push(`commitRequired: ${workOrder.git.commitRequired}`);
  lines.push(`PR creationAllowed: ${workOrder.pr.creationAllowed}`);
  lines.push(`PR creationRequired: ${workOrder.pr.creationRequired}`);
  lines.push(`PR mergeAllowed: ${workOrder.pr.mergeAllowed}`);
  lines.push("");

  if (workOrder.rendering.includeStopConditions) {
    lines.push("==================================================");
    lines.push("STOP CONDITIONS");
    lines.push("==================================================");
    for (const stop of workOrder.stopConditions) {
      lines.push(`- [${stop.id}] ${stop.condition} → ${stop.requiredOutcome}`);
    }
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("ALLOWED TERMINAL VERDICTS");
  lines.push("==================================================");
  for (const v of workOrder.completion.allowedTerminalVerdicts) {
    lines.push(`- ${v}`);
  }
  lines.push("");

  lines.push(
    trustedSha
      ? `Begin by verifying repository identity: run git rev-parse HEAD; if needed, materialize Radio-authorized source ${trustedBranch}@${trustedSha}; confirm exact HEAD equality before any other work.`
      : "Begin by verifying repository identity: run git rev-parse HEAD and confirm the exact trusted tip before any other work.",
  );
  lines.push(
    "End by emitting schema-valid completion-report JSON inside exactly one fenced `text` block — including for BLOCKED/HALT_PRECHECK outcomes.",
  );
  return lines.join("\n");
}
