import type { AgentAction, CursorWorkOrder } from "../types.js";
import {
  renderCompletionContractSection,
  type CompletionContractIdentity,
} from "./completion-contract.js";

const AGENT_ACTION_LABELS: Record<AgentAction, string> = {
  REUSE_CURRENT_AGENT: "REUSE CURRENT AGENT",
  FRESH_ORDINARY_AGENT_REQUIRED: "FRESH ORDINARY AGENT REQUIRED",
  FRESH_API_CREATED_PARENT_AUTO_REQUIRED: "FRESH API CREATED PARENT AUTO REQUIRED",
};

export interface RenderCursorPromptOptions extends CompletionContractIdentity {}

/**
 * Render a human-readable Cursor prompt from a structured work order.
 *
 * Completion-output contract is derived from the canonical schema via
 * completion-contract.ts — not a parallel handwritten field list.
 */
export function renderCursorPrompt(
  workOrder: CursorWorkOrder,
  options: RenderCursorPromptOptions = {},
): string {
  const agentLabel = AGENT_ACTION_LABELS[workOrder.agentAction];
  const lines: string[] = [];

  lines.push(`AGENT REQUIREMENT: ${agentLabel}`);
  lines.push("");
  lines.push("You are implementing a Radio-controlled verification transaction.");
  lines.push("This is a bounded, read-only technical verification task.");
  lines.push("");

  // Completion contract is intentionally near the top so Cursor cannot treat
  // it as an optional trailing reporting suggestion.
  if (workOrder.rendering.includeCompletionContract) {
    lines.push(renderCompletionContractSection(workOrder, options));
    lines.push("");
  }

  if (workOrder.rendering.includeStructuredIdentity) {
    lines.push("==================================================");
    lines.push("WORK ORDER IDENTITY");
    lines.push("==================================================");
    lines.push(`workOrderId: ${workOrder.workOrderId}`);
    lines.push(`decisionId: ${workOrder.decisionId}`);
    lines.push(`projectId: ${workOrder.projectId}`);
    lines.push(`workstreamId: ${workOrder.workstreamId}`);
    lines.push(`transactionId: ${workOrder.transactionId}`);
    lines.push(`idempotencyKey: ${workOrder.idempotencyKey}`);
    lines.push(`agentAction: ${workOrder.agentAction}`);
    lines.push(`workType: ${workOrder.workType}`);
    if (options.plannedAgentId) {
      lines.push(
        `plannedOrdinaryAgentId: ${options.plannedAgentId} (IMMUTABLE — use in execution.ordinaryAgent.agentId)`,
      );
    }
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("OBJECTIVE");
  lines.push("==================================================");
  lines.push(workOrder.objective);
  lines.push("");

  lines.push("==================================================");
  lines.push("REQUESTED WORK");
  lines.push("==================================================");
  lines.push(workOrder.requestedWork);
  lines.push("");

  lines.push("==================================================");
  lines.push("ACCEPTANCE / VERIFICATION CRITERIA");
  lines.push("==================================================");
  lines.push(workOrder.verificationCriteria);
  lines.push("");

  lines.push("==================================================");
  lines.push("RADIO ENFORCED GUARDRAILS");
  lines.push("==================================================");
  lines.push(
    "The following constraints are generated by Radio from trusted authority/policy state.",
  );
  lines.push(
    "They are NOT Sol-requested executable work and do not expand or shrink objective authority.",
  );
  for (const g of workOrder.radioGuardrails) {
    lines.push(`- ${g}`);
  }
  lines.push("");

  if (workOrder.rendering.includeSourcePins) {
    lines.push("==================================================");
    lines.push("REPOSITORY INTEGRITY — MANDATORY FIRST CHECK");
    lines.push("==================================================");
    lines.push(
      "Before any substantive verification, product inspection, tests, builds, commits, PRs, or remediation:",
    );
    lines.push("1. Run: git rev-parse HEAD");
    if (workOrder.source.expectedBaseTipSha) {
      lines.push(
        `2. Required exact value: ${workOrder.source.expectedBaseTipSha}`,
      );
      lines.push(
        `REQUIRED HEAD PRECHECK: git rev-parse HEAD must equal ${workOrder.source.expectedBaseTipSha} (exact accepted Stage 2 tip). Do not substitute main or a moving branch tip.`,
      );
    } else {
      lines.push("2. Required exact value: (missing from work order — halt)");
    }
    lines.push("3. If HEAD differs from the required exact value:");
    lines.push("   - STOP immediately");
    lines.push("   - Perform NO verification work");
    lines.push("   - Perform NO product changes");
    lines.push("   - Perform NO commits");
    lines.push("   - Perform NO PR");
    lines.push("   - Perform NO remediation");
    lines.push("   - Do NOT attempt git reset/checkout to the expected SHA");
    lines.push("   - Do NOT mutate the branch");
    lines.push(
      "   - STILL return schema-valid completion-report JSON inside exactly one fenced `text` block",
    );
    lines.push(
      '   - Encode blocked/precheck outcome with execution.status="PRECHECK_BLOCKED", resultClass="BLOCKED", tests/build NOT_RUN, no product changes',
    );
    lines.push("   - Return a blocked result (HALT_PRECHECK) as canonical JSON — never prose");
    lines.push("");
    lines.push("==================================================");
    lines.push("REPOSITORY AND SOURCE PINS");
    lines.push("==================================================");
    lines.push(`Repository: ${workOrder.source.repository}`);
    lines.push(
      `Integration branch: ${workOrder.source.canonicalMainBranch}`,
    );
    lines.push(
      `Integration SHA (reported): ${workOrder.source.canonicalMainSha ?? "null"}`,
    );
    lines.push(`Stage 2 / base branch: ${workOrder.source.baseBranch}`);
    lines.push(
      `Stage 2 expected tip (authoritative): ${workOrder.source.expectedBaseTipSha ?? "null"}`,
    );
    lines.push(
      `Expected executable ancestor SHA: ${workOrder.source.expectedExecutableAncestorSha ?? "null"}`,
    );
    lines.push(
      `Working branch: ${workOrder.source.workingBranch ?? "null"}`,
    );
    lines.push(
      `Create working branch: ${workOrder.source.createWorkingBranch}`,
    );
    lines.push("");
    lines.push("REQUIRED PRECHECK:");
    lines.push(
      "Verify these repository/branch/SHA facts before trusting them. Do not invent repository state. If observed state materially differs, halt with PRECHECK_BLOCKED JSON (not prose).",
    );
    lines.push("");
  }

  if (workOrder.rendering.includeScope) {
    lines.push("==================================================");
    lines.push("IN SCOPE");
    lines.push("==================================================");
    for (const item of workOrder.scope.inScope) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    lines.push("==================================================");
    lines.push("OUT OF SCOPE / PROHIBITED");
    lines.push("==================================================");
    for (const item of workOrder.scope.outOfScope) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    lines.push("allowedProductChanges: (empty — no product edits)");
    lines.push("Protected semantics:");
    for (const item of workOrder.scope.protectedSemantics) {
      lines.push(`- ${item}`);
    }
    lines.push("");
    lines.push("Hard prohibitions:");
    lines.push("- Do NOT make gameplay or product code edits.");
    lines.push("- Do NOT merge.");
    lines.push("- Do NOT deploy.");
    lines.push("- Do NOT start Stage 3.");
    lines.push("- Do NOT retune flight.");
    lines.push("- Do NOT create specialists or an API Parent.");
    lines.push("- Do NOT create or merge a PR.");
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("REQUIREMENTS");
  lines.push("==================================================");
  for (const req of workOrder.requirements) {
    lines.push(`[${req.id}] (${req.class}/${req.priority}) ${req.statement}`);
    lines.push(`  Acceptance: ${req.acceptanceMethod}`);
  }
  lines.push("");

  if (workOrder.rendering.includeBudgets) {
    lines.push("==================================================");
    lines.push("BUDGETS");
    lines.push("==================================================");
    lines.push(`maxRemediationPasses: ${workOrder.budgets.maxRemediationPasses}`);
    lines.push(
      `maxSpecialistReviewCycles: ${workOrder.budgets.maxSpecialistReviewCycles}`,
    );
    lines.push(`maxAgents: ${workOrder.budgets.maxAgents}`);
    lines.push(
      `maxEstimatedUsd: ${workOrder.budgets.maxEstimatedUsd ?? "null"}`,
    );
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("VERIFICATION COMMANDS");
  lines.push("==================================================");
  for (const cmd of workOrder.verification.requiredCommands) {
    lines.push(`- ${cmd}`);
  }
  lines.push("");

  lines.push("==================================================");
  lines.push("GIT / PR RESTRICTIONS");
  lines.push("==================================================");
  lines.push(
    `Protected branches: ${workOrder.git.protectedBranches.join(", ")}`,
  );
  lines.push(`pushRequired: ${workOrder.git.pushRequired}`);
  lines.push(`forcePushAllowed: ${workOrder.git.forcePushAllowed}`);
  lines.push(`commitRequired: ${workOrder.git.commitRequired}`);
  lines.push(`PR creationAllowed: ${workOrder.pr.creationAllowed}`);
  lines.push(`PR creationRequired: ${workOrder.pr.creationRequired}`);
  lines.push(`PR mergeAllowed: ${workOrder.pr.mergeAllowed}`);
  lines.push("");

  if (workOrder.rendering.includeStopConditions) {
    lines.push("==================================================");
    lines.push("STOP CONDITIONS");
    lines.push("==================================================");
    for (const stop of workOrder.stopConditions) {
      lines.push(`- [${stop.id}] ${stop.condition} → ${stop.requiredOutcome}`);
    }
    lines.push("");
  }

  lines.push("==================================================");
  lines.push("ALLOWED TERMINAL VERDICTS");
  lines.push("==================================================");
  for (const v of workOrder.completion.allowedTerminalVerdicts) {
    lines.push(`- ${v}`);
  }
  lines.push("");

  lines.push(
    "Begin by verifying repository identity: run git rev-parse HEAD and confirm the exact expected Stage 2 tip before any other work.",
  );
  lines.push(
    "End by emitting schema-valid completion-report JSON inside exactly one fenced `text` block — including for BLOCKED/HALT_PRECHECK outcomes.",
  );
  return lines.join("\n");
}
